#!/bin/sh
# ============================================================================
# build.sh — assemble the self-contained roo_fix install.sh monolith.
#
# Local (development) tool, never shipped to the router:
#   1. validates payloads/ against metadata/fingerprints.conf (canonical md5s)
#   2. base64-encodes each payload
#   3. concatenates src/*.sh + the embedded payload table into install.sh
#
# Usage:  build.sh           (writes ./install.sh + ./install.sh.md5)
#         BUILD_VER=1.1.3 build.sh   (version stamp override)
# ============================================================================
set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"

OUT="install.sh"
CONF="metadata/fingerprints.conf"

# src/00-header.sh is the SINGLE source of truth for the version. This used to
# be the other way round: VER defaulted to a literal 1.1.0 and the stamp was a
# sed against that same literal. Bumping the version the natural way (editing
# the header) therefore silently no-op'd the stamp while the build went on
# REPORTING 1.1.0 for an artifact that was actually something else. A build
# that misreports its own version cannot be trusted to report anything.
VER="$(sed -n 's/^VERSION="\(.*\)"$/\1/p' src/00-header.sh | head -1)"
[ -n "$VER" ] || { echo "build.sh: no VERSION= found in src/00-header.sh" >&2; exit 1; }
[ -n "${BUILD_VER:-}" ] && VER="$BUILD_VER"

[ -f "$CONF" ] || { echo "build.sh: missing $CONF" >&2; exit 1; }

# ---------------------------------------------------------------- sanity
# every src fragment must at least parse standalone before assembly
for f in src/00-header.sh src/10-lib.sh src/20-detect.sh src/30-payloads.sh \
         src/40-fix-ipv6.sh src/50-fix-ttl.sh src/60-fix-preserve.sh src/70-main.sh; do
	[ -f "$f" ] || { echo "build.sh: missing $f" >&2; exit 1; }
	sh -n "$f" || { echo "build.sh: syntax error in $f" >&2; exit 1; }
done
echo "src fragments: syntax OK"

# ---------------------------------------------------------------- validate
line=0
while IFS='|' read -r name dest mode canon olds missing || [ -n "$name" ]; do
	line=$((line+1))
	case "$name" in ''|\#*) continue ;; esac
	# strip possible CR
	name="$(printf '%s' "$name" | tr -d '\r')"
	payload="payloads/$name"
	[ -f "$payload" ] || { echo "build.sh: payload '$payload' missing (conf line $line)" >&2; exit 1; }
	got="$(md5sum "$payload" | cut -d' ' -f1)"
	if [ "$got" != "$canon" ]; then
		echo "build.sh: payload md5 MISMATCH for $name (conf expects $canon, got $got)" >&2
		exit 1
	fi
	# install-if-missing must be exactly 0 or 1. Anything else would silently
	# read as "absent means do nothing" in the installer, which is the one
	# default that must never be reached by a typo.
	case "$missing" in
		0|1) : ;;
		*) echo "build.sh: $name has install-if-missing='$missing', must be 0 or 1 (conf line $line)" >&2; exit 1 ;;
	esac
	echo "ok: $name  $canon  -> $dest  (install-if-missing=$missing)"
done < "$CONF"
echo "payloads validated against fingerprint table"

# ------------------------------------------------------------ assemble
T="$(mktemp -d "${TMPDIR:-/tmp}/roofix-build.XXXXXX")"
trap 'rm -rf "$T"' EXIT

OUTT="$T/install.sh"
{
	# header with version stamp (matches whatever the header currently says,
	# not a hardcoded literal)
	sed "s/^VERSION=\".*\"$/VERSION=\"$VER\"/" src/00-header.sh
	printf '\n'

	# libs
	cat src/10-lib.sh;      printf '\n'
	cat src/20-detect.sh;   printf '\n'

	# embedded payload table (between the assignment markers)
	printf '%s\n' '# embedded payload table — generated by build.sh, do not edit'
	printf '%s\n' 'ROOTUP_TABLE="\'
	while IFS='|' read -r name dest mode canon olds missing || [ -n "$name" ]; do
		case "$name" in ''|\#*) continue ;; esac
		name="$(printf '%s' "$name" | tr -d '\r')"
		payload="payloads/$name"
		b64="$(base64 -w0 < "$payload")"
		printf '%s|%s|%s|%s|%s|%s|%s\n' "$name" "$dest" "$mode" "$canon" "$olds" "$missing" "$b64"
	done < "$CONF"
	printf '%s\n' '"'
	printf '\n'

	# ops
	cat src/30-payloads.sh;     printf '\n'
	cat src/40-fix-ipv6.sh;     printf '\n'
	cat src/50-fix-ttl.sh;      printf '\n'
	cat src/60-fix-preserve.sh; printf '\n'
	cat src/70-main.sh;         printf '\n'
} > "$OUTT"

# the \"\\\n continuation trick must not leak a trailing backslash into the
# final line+quote; verify the assignment parses as one logical line
sh -n "$OUTT" || { echo "build.sh: generated script fails sh -n" >&2; exit 1; }

# The version in the artifact must be the version being reported. This is the
# check that would have caught the 1.1.0/actual mismatch above.
got_ver="$(sed -n 's/^VERSION="\(.*\)"$/\1/p' "$OUTT" | head -1)"
[ "$got_ver" = "$VER" ] || {
	echo "build.sh: version stamp mismatch (reporting $VER, artifact says '${got_ver:-<none>}')" >&2
	exit 1
}

cp "$OUTT" "$OUT"
md5sum "$OUT" | cut -d' ' -f1 > "$OUT.md5"
echo
echo "built: $OUT  ($(wc -c < "$OUT") bytes, md5 $(cat "$OUT.md5"))"
echo "version: $VER"
echo "syntax: sh -n PASS"